### ISSUE TITLE
Failure to open wayland applications on core-image-weston with R32.5 / meta-tegra master branch

### ISSUE THREAD

**Issue by mozcelikors** [OE4T/meta-tegra#628]
I was using R32.4 branches and was able to display apps on Xwayland (core-image-weston):

`XDG_RUNTIME_DIR=/run/user/0 gst-launch-1.0 videotestsrc ! waylandsink`

would get me a test video on wayland display.

However, recently I updated every branch to master (R32.5) (to be able to use latest gst plugins), now the same command does not work.

poky, meta-openembedded, meta-tegra are all at master. Compilation is successful, but wayland seems broken now. Demo apps including Qt apps does not work now.

Similarly, I was able to run tensorrt_demos by specifying DISPLAY=:0, now I get:

`Can't initialize GTK backend in function 'cvInitSystem'`

`journalctl | grep display` returns that xserver is attached to :0.

Is there some change to Xwayland that I don't know about in the recent branches?
Thanks in advance.

**Comment by madisongh** [comment]
There were some changes to weston in poky/OE-Core master a while back that I only recently caught up with. It should work better in master now - the gstreamer pipeline works OK for me (without setting XDG_RUNTIME_DIR, since weston is now started under username 'weston'), and Xwayland is working again (but still without accelerated OpenGL support, as far as I can tell).
