### ISSUE TITLE
Weston is broken on master

### ISSUE THREAD

**Issue by madisongh** [OE4T/meta-tegra#897]
**Describe the bug**
OE-Core master has upgraded to Weston 10.0.0, and integration on the Jetson platforms has not yet been completed.
The EGLStreams patches we had been using with Weston 9.0.0 have not been ported to the new version.

**To Reproduce**
Build `demo-image-weston` on the demo distro master branch.
Build succeeds, but `weston.service` fails to start.

**Additional context**
Possible options:
1. Re-port the EGLStreams patches. This may or may not be possible.
2. Try converting to using the GBM back-end and adapt the [EGL backend](https://github.com/NVIDIA/egl-gbm) for `libgbm`.  This may or may not work.
3. Pull the Weston 9.0.0 recipe into the layer and have the tegra platforms prefer that version, instead of upgrading.

**Comment by kekiefer** [comment]
Weston EGL clients are now working by updating just the patches that add support for the wl_eglstream_controller. This is a good result, since we are still able to use Weston's GBM backend, greatly reducing the modifications required to make this work.

Although functional now, I do plan to replace the Mesa GBM patches with a loadable wrapper for libnvgbm so we can support the backend without having to mess with Mesa. After this is done I'll submit a PR and we should be good to go.

WIP branch can be found here: https://github.com/kekiefer/meta-tegra/tree/wip-weston-10
